High Speed Numerical Array Computation using Numpy Module

Installing Numpy and Numpy Array Creation

In [ ]:
# Install a pip package in the current Jupyter kernel
# ! pip install numpy

In [3]:
lst = [1,2,3,4,5,6]
print(type(lst))
print('List: ', lst)

<class 'list'>
List:  [1, 2, 3, 4, 5, 6]


In [4]:
# Importing the numpy library
import numpy as np
arr = np.array(lst)
print(type(arr))
print('Numpy array: ',arr)

<class 'numpy.ndarray'>
Numpy array:  [1 2 3 4 5 6]


In [5]:
# Creating a simple array in numpy

arr = np.array([1, 2, 3, 4])

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [1 2 3 4]


In [6]:
# Creating a simple array in numpy using np.arange

arr = np.arange(10)

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [0 1 2 3 4 5 6 7 8 9]


Why Numpy?
Most powerful numerical processing library in python. Array Oriented computing.
Provides extension package to python for multi dimensional array.
Very efficient.
Scientific computation.

But WHY numpy, when we already have lists?

In [7]:
%%time
lst = list(range(1000000))
for i in range(1000000):
    lst[i] *= lst[i]
    

CPU times: user 472 ms, sys: 92.6 ms, total: 565 ms
Wall time: 910 ms


In [8]:
%%time

arr = np.arange(1000000)
arr = arr * arr

CPU times: user 0 ns, sys: 82.3 ms, total: 82.3 ms
Wall time: 339 ms


Numpy Array and It's Attributes/Properties

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 2 3 4]
Shape:  (4,)
Data Type:  int64
Item Size:  8
Dimensionality:  1


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Data Type:  int64
Item Size:  8
Dimensionality:  2


Functions for creating Numpy Array

In [11]:
arr = np.arange(10)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [0 1 2 3 4 5 6 7 8 9]
Shape:  (10,)
Data Type:  int64
Item Size:  8
Dimensionality:  1


In [12]:
arr = np.arange(1, 10)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 2 3 4 5 6 7 8 9]
Shape:  (9,)
Data Type:  int64
Item Size:  8
Dimensionality:  1


In [15]:
# To print even numbers
arr = np.arange(2,51,2)
print('Even number between 0-51: ',arr)

Even number between 0-51:  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [17]:
# To print odd numbers
arr = np.arange(1,50,2)
print('Odd numberss between 0-50: ',arr)

Odd numberss between 0-50:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [22]:
# np.ones
arr = np.ones((4,4), dtype= int)
print(arr) # prints 4rows and 4columns

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [23]:
# np.zeros
arr = np.zeros((4,4), dtype= int)
print(arr) # prints 4rows and 4columns

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [24]:
# np.eyes
arr = np.eye(3)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


Datatypes in Numpy
Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
str - string
f - float
m - timedelta
M - datetime
O - object
u - unsigned integer
c - complex float
U - unicode string
V - fixed chunk of memory for other type ( void )

In [27]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='f')
print("Array: \n", arr)
# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2. 1. 4. 5.]
Data Type:  float32


In [28]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='O')
print("Array: \n", arr)
# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2 1 4 5]
Data Type:  object


## Numpy Random Numbers
np.random.rand - generates an array with random numbers that are uniformly distribute between 0 and 1.
np.random.randn - generates an array with random numbers that are normally distributed, mean = 0 and stdev = 1.
np.random.randint - generates an array with random numbers (integers) that are uniformly distribute between 0 and given number.
np.random.uniform - generates an array with random numbers (float) between given numbers.

In [29]:
import numpy as np

arr = np.random.rand(5)

print("Numpy Array: \n", arr)

Numpy Array: 
 [0.91311267 0.02719265 0.8955667  0.59263949 0.90167596]


In [30]:
# Randomly generate an array with 10 rows and 2 columns
arr = np.random.rand(10, 2)

print("Numpy Array generated randomly from uniform distribution: \n", arr)

Numpy Array generated randomly from uniform distribution: 
 [[0.63191827 0.62604073]
 [0.26839833 0.46727688]
 [0.73664338 0.3829104 ]
 [0.83238977 0.77203049]
 [0.49849042 0.35980221]
 [0.56811285 0.49908811]
 [0.71556547 0.33531876]
 [0.14172557 0.82472822]
 [0.05773253 0.13271412]
 [0.2344864  0.18505771]]


In [31]:
# Randomly generate an array from normal distribution

arr = np.random.randn(5)
print("Numpy Array: \n", arr)

Numpy Array: 
 [-0.24492265  0.09799667 -0.41831612 -2.61199788 -1.34774072]


In [32]:
# Randomly generate an array with 5 rows and 4 columns
arr = np.random.randn(5, 4)

print("Numpy Array generated randomly from normal distribution: \n", arr)

Numpy Array generated randomly from normal distribution: 
 [[ 1.02029308e+00  1.54016324e+00 -3.24063809e-01 -7.83518730e-01]
 [-7.40756128e-01 -5.98052597e-01  2.37538679e-01 -9.82687516e-01]
 [-4.99849665e-01  1.54321973e+00 -1.37989805e+00  1.13815951e-01]
 [-1.05848827e-03 -5.83954418e-01 -4.26441504e-01 -4.16051612e-01]
 [ 2.46925204e+00 -1.08674832e+00  9.63738208e-01  2.06498585e-02]]


In [33]:
value = np.random.randint(10)

print(value)

3


In [48]:
# simple game
guess = int(input('Guess the number: '))
value = np.random.randint(10)
def guessing():
    while True:
        if guess == value:
            print('Correct', value)
        elif guess > value:
            print('Too high', value)
            break
        elif guess < value:
            print('Too low ', value)
            break
        else:
           pass
guessing()

print('Thanks for guessing')

Too high 0
Thanks for guessing


In [50]:
# Randomly generate a 5*4 array containing values in the range of 0 to 9
arr = np.random.randint(10, size = (5, 4))
print("Numpy Array: \n", arr)
print(arr.ndim)

Numpy Array: 
 [[3 2 5 4]
 [6 3 3 3]
 [4 3 0 6]
 [4 1 6 9]
 [8 6 0 3]]
2


In [51]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[30 35 25 27 34 32 27 15 31 10]
 [30 13 12 22 28 20 38 25 18 26]
 [29 25 25 25 16 16 29 32 31 17]
 [36 30 21 37 19 34 12 12 17 11]
 [23 14 28 16 16 23 15 28 13 32]]


In [52]:
# Generate one random decimal value between 0 to 10
value = np.random.uniform(10)
print(value)

5.148639137614059


In [53]:
# Randomly generate a 5*4 array containing values in the range of 0 to 10
arr = np.random.uniform(10, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[6.62689092 8.06335934 9.02482093 2.67635108]
 [7.82658207 7.24825975 3.54588463 6.91335816]
 [8.81664017 3.46321955 2.58593616 4.84185441]
 [1.58901821 5.04110632 4.66671875 7.81576859]
 [8.53726656 7.3912787  6.02112026 8.18883513]]


Numpy Array - Indexing, Slicing and Updating
Since data in numpy array is stored sequentially, it is possible to access the data with the help of Indexing and Slicing operation. NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

Also remember that numpy array's are mutable. i.e. Data stored in numpy array can be updated/changed.

Data Accessing using Indexing in Numpy Array

In [60]:
# Randomly generating 1 dimensional array
arr = np.random.randint(100, size = (5, ))
print("Numpy Array: \n", arr)
print("Shape: ", arr.shape)

Numpy Array: 
 [76 56 48  5 50]
Shape:  (5,)


In [61]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  48


In [62]:
# Accessing 4th index
print("Value at 5th index: ", arr[4])

Value at 5th index:  50


In [71]:
# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))
print("Numpy Array: \n", arr)

Numpy Array: 
 [[66 17 73 96]
 [ 4 53 42 98]
 [50 46 20 86]
 [31 62 59 32]
 [65 71 98 31]]


In [73]:
# Data Accessing using Slicing in Numpy Array
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))
print("Numpy Array: \n", arr)
print("Shape: ", arr.shape)

Numpy Array: 
 [ 6 12 50 47 95 69 83 92 40 47]
Shape:  (10,)


In [74]:
print(arr[1:4])
print(arr[0:-4])
print(arr[::2])

[12 50 47]
[ 6 12 50 47 95 69]
[ 6 50 95 83 40]


In [75]:
# Indexing with Boolean Arrays
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [78 32 20 67 43 18 48 81 13 81]
Shape:  (10,)


In [77]:
idx = [True, True, False, False, False, True, False, False, True, True]

print(arr[idx])

[78 32 18 13 81]


In [80]:
# Updating value in the array

# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Original Array: \n", arr)

arr[2, 2] = 99

print("Updated Array: \n", arr)

Original Array: 
 [[34 90 96 33]
 [52 43 91 35]
 [26 30 79 99]
 [16 39 69 45]
 [88 54 27 68]]
Updated Array: 
 [[34 90 96 33]
 [52 43 91 35]
 [26 30 99 99]
 [16 39 69 45]
 [88 54 27 68]]


Numpy Flatten and Ravel

In [82]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))
print("Numpy Array: \n", arr)
print("Shape: ", arr.shape)

Numpy Array: 
 [[18 21 21 17 27 18 23 26 26 27]
 [13 21 15 31 17 22 28 14 32 17]
 [10 35 14 25 34 11 20 27 10 34]
 [29 17 33 28 37 27 10 14 31 33]
 [15 33 22 12 22 30 24 31 23 25]]
Shape:  (5, 10)


In [83]:
flatten_arr = arr.flatten()

print("Flatten Array: \n", flatten_arr)
print("Shape: ", flatten_arr.shape)

Flatten Array: 
 [18 21 21 17 27 18 23 26 26 27 13 21 15 31 17 22 28 14 32 17 10 35 14 25
 34 11 20 27 10 34 29 17 33 28 37 27 10 14 31 33 15 33 22 12 22 30 24 31
 23 25]
Shape:  (50,)


In [85]:
ravel_arr = arr.ravel()

print("Ravel Array: \n", ravel_arr)
print("Shape: ", ravel_arr.shape)

Ravel Array: 
 [18 21 21 17 27 18 23 26 26 27 13 21 15 31 17 22 28 14 32 17 10 35 14 25
 34 11 20 27 10 34 29 17 33 28 37 27 10 14 31 33 15 33 22 12 22 30 24 31
 23 25]
Shape:  (50,)


In [86]:
print("Flatten Array: \n", flatten_arr)

print("Ravel Array: \n", ravel_arr)

Flatten Array: 
 [18 21 21 17 27 18 23 26 26 27 13 21 15 31 17 22 28 14 32 17 10 35 14 25
 34 11 20 27 10 34 29 17 33 28 37 27 10 14 31 33 15 33 22 12 22 30 24 31
 23 25]
Ravel Array: 
 [18 21 21 17 27 18 23 26 26 27 13 21 15 31 17 22 28 14 32 17 10 35 14 25
 34 11 20 27 10 34 29 17 33 28 37 27 10 14 31 33 15 33 22 12 22 30 24 31
 23 25]


Observation
Ravel is faster than flatten() as it does not occupy any memory. Ravel returns a view of the original array.

Numpy Reshape

In [2]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
import numpy as np
arr = np.random.randint(10, 40, size = (5, 10))
print("Numpy Array: \n", arr)
print("Shape: ", arr.shape)

Numpy Array: 
 [[16 30 35 29 28 30 37 13 35 34]
 [20 29 34 29 15 34 13 34 39 21]
 [25 38 37 14 23 30 10 19 39 11]
 [13 32 38 33 37 14 16 34 21 19]
 [28 27 21 28 37 12 25 11 10 14]]
Shape:  (5, 10)


In [3]:
re_shape = arr.reshape(10,5)
print(re_shape)

[[16 30 35 29 28]
 [30 37 13 35 34]
 [20 29 34 29 15]
 [34 13 34 39 21]
 [25 38 37 14 23]
 [30 10 19 39 11]
 [13 32 38 33 37]
 [14 16 34 21 19]
 [28 27 21 28 37]
 [12 25 11 10 14]]


Iterating over Numpy Array
Iterating over a 1 Dimensional Array

In [5]:
# Randomly generate an array containing values in the range of 10 to 39
import numpy as np

arr1d = np.random.randint(5,40, size=(5,))
print(arr1d)

[19 34 16  5 36]


In [7]:
# looping over items in the array
for item in arr1d:
    print(item, end=' ')

19 34 16 5 36 

Iterating over a 2 Dimensional Array

In [8]:
arr2d = np.random.randint(10,40 , size=(5,10))
print(arr2d)

[[32 16 12 29 37 17 21 30 15 22]
 [36 28 35 18 17 10 28 35 27 26]
 [30 31 12 18 12 16 25 34 30 36]
 [18 34 20 19 37 35 32 10 22 24]
 [22 12 18 28 12 18 21 10 36 30]]


In [9]:
# looping over rows in the 2d array
for row in arr2d:
    print(row)

[32 16 12 29 37 17 21 30 15 22]
[36 28 35 18 17 10 28 35 27 26]
[30 31 12 18 12 16 25 34 30 36]
[18 34 20 19 37 35 32 10 22 24]
[22 12 18 28 12 18 21 10 36 30]


In [11]:
# looping over rows in the 2d array
for row in arr2d.ravel():
    print(row, end=' ')

32 16 12 29 37 17 21 30 15 22 36 28 35 18 17 10 28 35 27 26 30 31 12 18 12 16 25 34 30 36 18 34 20 19 37 35 32 10 22 24 22 12 18 28 12 18 21 10 36 30 

Iterating using np.nditer()

In [13]:
for item in np.nditer(arr1d):
    print(item, end=' ')

19 34 16 5 36 

In [14]:
for row in np.nditer(arr2d):
    print(row, end=' ')

32 16 12 29 37 17 21 30 15 22 36 28 35 18 17 10 28 35 27 26 30 31 12 18 12 16 25 34 30 36 18 34 20 19 37 35 32 10 22 24 22 12 18 28 12 18 21 10 36 30 

In [15]:
print("Original Array: ", arr1d)
for item in np.nditer(arr1d, op_flags=['readwrite']):
    if item > 20:
        item[...] = (item*0)
print('updated array: ', arr1d)


Original Array:  [19 34 16  5 36]
updated array:  [19  0 16  5  0]


Exercise: Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all odd numbers with -1. (Using a Loop)

In [16]:
# step1:
arr = np.random.randint(5,50, size=(5,4))
print(arr)


[[22 43 41 31]
 [27 14 19  7]
 [41 46 40 30]
 [13 40 40 44]
 [25 21 25 35]]


In [21]:
#step2: to perform update
for item in np.nditer(arr, op_flags=['readwrite']):
    if item%2 == 1:
        item[...] = (item)
print(arr)

[[ 22 -43 -41 -31]
 [-27  14 -19  -7]
 [-41  46  40  30]
 [-13  40  40  44]
 [-25 -21 -25 -35]]


Exercise2: Given an array [1, -10, 2, 3, 0, 6], print the array in this order [0, 6, -10, 2, 1, 3]

- Python Operators on Numpy Array
We can apply any python operator on Numpy Array.
It will perform the operation on each element of a numpy array.

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

In [22]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.ndim)
print("Original Array: \n", x)

2
Original Array: 
 [[1 2 3]
 [4 5 6]]


In [23]:
print(x+5)

[[ 6  7  8]
 [ 9 10 11]]


In [24]:
print(x%2)

[[1 0 1]
 [0 1 0]]


In [25]:
print(x >=3)

[[False False  True]
 [ True  True  True]]


Exercise: Write a program to filter the values from the array based on below mentioned conditions:
Either value should be divisible by 5.
(or) value should be an odd number and factor of 7.

Numpy Maths
Reference: https://numpy.org/doc/stable/reference/routines.math.html

In [26]:
print("Square Root: ", np.sqrt(4))

print("Exponent: ", np.exp(1))

print("Trigonometric Sin: ", np.sin(0))

print("Trigonometric Cos: ", np.cos(0))

print("... and many more")

Square Root:  2.0
Exponent:  2.718281828459045
Trigonometric Sin:  0.0
Trigonometric Cos:  1.0
... and many more


In [27]:
arr = np.array([1, 2, 3, 4])

print("Square Root: ", np.sqrt(arr))
print("Exponent: ", np.exp(arr))
print("Trigonometric Sin: ", np.sin(arr))
print("Trigonometric Cos: ", np.cos(arr))

Square Root:  [1.         1.41421356 1.73205081 2.        ]
Exponent:  [ 2.71828183  7.3890561  20.08553692 54.59815003]
Trigonometric Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Trigonometric Cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [28]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

print("Elementwise Addition: \n", np.add(x, y))
print("Elementwise Subtraction: \n", np.subtract(x, y))
print("Elementwise Multiplication: \n", np.multiply(x, y))
print("Elementwise Division: \n", np.divide(x, y))

Elementwise Addition: 
 [[ 6  8]
 [10 12]]
Elementwise Subtraction: 
 [[-4 -4]
 [-4 -4]]
Elementwise Multiplication: 
 [[ 5 12]
 [21 32]]
Elementwise Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


Matrix multiplication

In [29]:
import numpy as np

x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

print("Matrix Multiplication (Way-1): \n", np.matmul(x, y))
print("Matrix Multiplication (Way-2): \n", np.dot(x, y))
print("Matrix Multiplication (Way-3): \n", x @ y)

Matrix Multiplication (Way-1): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-2): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-3): 
 [[19 22]
 [43 50]]


Diagonal elements

In [30]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)
print("Diagonal: ", np.diag(x))

Original Array: 
 [[1 2 3]
 [4 5 6]]
Diagonal:  [1 5]


Transpose of an array

In [31]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)
print()
print("Transpose: \n", x.T)

Original Array: 
 [[1 2 3]
 [4 5 6]]

Transpose: 
 [[1 4]
 [2 5]
 [3 6]]


Numpy Statistics

In [32]:
x = np.array([[1,2], [3,4]])

print("Array: \n", arr)
print("Sum: ", np.sum(x))
print("Columnwise Sum: ", np.sum(x, axis=0)) # Column Wise
print("Rowwise Sum: ", np.sum(x, axis=1)) # Row wise

Array: 
 [1 2 3 4]
Sum:  10
Columnwise Sum:  [4 6]
Rowwise Sum:  [3 7]


In [33]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)
print("Minimum: ", np.min(x))
print("Columnwise Minimum: ", np.min(x, axis=0)) # Column Wise
print("Rowwise Minimum: ", np.min(x, axis=1)) # Row wise

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Columnwise Minimum:  [1 2 3]
Rowwise Minimum:  [1 4]


In [34]:
x = np.array([160, 180, 146, 162, 184, 180])

print("Array: \n", x)
print("Minimum: ", np.min(x))
print("Maximum: ", np.max(x))
print("Mean: ", np.mean(x))
print("Median: ", np.median(x))
print("Variance: ", np.var(x))
print("Std Dev: ", np.std(x))

Array: 
 [160 180 146 162 184 180]
Minimum:  146
Maximum:  184
Mean:  168.66666666666666
Median:  171.0
Variance:  187.55555555555557
Std Dev:  13.695092389449425


In [35]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)
print("Minimum: ", np.min(x))
print("Maximum: ", np.max(x))
print("Mean: ", np.mean(x))
print("Median: ", np.median(x))
print("Variance: ", np.var(x))
print("Std Dev: ", np.std(x))

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Maximum:  6
Mean:  3.5
Median:  3.5
Variance:  2.9166666666666665
Std Dev:  1.707825127659933


In [36]:
heights = np.array([160, 180, 146, 162, 184, 180])
weights = np.array([50, 78, 45, 51, 80, 60])
np.corrcoef(heights, weights)

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

#### Explore the following functions:
np.insert()
np.append()
np.delete()

Miscellaneous Topics

Linspace

In [37]:
print(np.linspace(2,6,4, dtype='int'))
# float by default


[2 3 4 6]


Sorting

In [38]:
arr = np.random.randint(50, 100, size = (5, 10))
print(arr)

[[64 98 59 54 67 84 78 89 96 87]
 [76 97 75 78 56 83 65 52 83 55]
 [58 89 51 71 67 85 79 53 57 94]
 [70 66 62 56 65 90 93 57 68 99]
 [52 74 54 65 65 96 59 97 70 80]]


In [39]:
np.sort(arr)

array([[54, 59, 64, 67, 78, 84, 87, 89, 96, 98],
       [52, 55, 56, 65, 75, 76, 78, 83, 83, 97],
       [51, 53, 57, 58, 67, 71, 79, 85, 89, 94],
       [56, 57, 62, 65, 66, 68, 70, 90, 93, 99],
       [52, 54, 59, 65, 65, 70, 74, 80, 96, 97]])

In [ ]:
# Column Wise Sorting

np.sort(arr, axis = 0)

In [40]:
# Row Wise Sorting

np.sort(arr, axis = 1)

array([[54, 59, 64, 67, 78, 84, 87, 89, 96, 98],
       [52, 55, 56, 65, 75, 76, 78, 83, 83, 97],
       [51, 53, 57, 58, 67, 71, 79, 85, 89, 94],
       [56, 57, 62, 65, 66, 68, 70, 90, 93, 99],
       [52, 54, 59, 65, 65, 70, 74, 80, 96, 97]])

Stacking

In [48]:
arr_1 = np.arange(0,15).reshape(3,5)
print(arr_1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [43]:
arr_2 = np.arange(20,35).reshape(3,5)
print(arr_2)

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


In [49]:
np.vstack([arr_1, arr_2]) # vertical stack

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [50]:
np.hstack([arr_1, arr_2]) #horizontal stack

array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

Concantenate

In [51]:
np.concatenate([arr_1, arr_2], axis = 0) # concatinating - vertical stacking

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [52]:
np.concatenate([arr_1, arr_2], axis = 1) # concatinating - horizontal stacking

array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

Append

In [53]:
np.append(arr_1, arr_2, axis = 0) # Appending - vertical stacking

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [54]:
np.append(arr_1, arr_2, axis = 1) # Appending - horizontal stacking

array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

Where - Process Array Elements Conditionally
Understanding np.where() Syntax
numpy.where(  
  condition,   # Where True, yield x, otherwise y  
  [x, y, ]     # Values to choose from  
)

In [55]:
arr = np.arange(50, 100).reshape(5, 10)

print(arr)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [56]:
np.where(arr > 64, 0, 1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
np.where(arr > 64, 0, arr)

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [62]:
np.where(arr > 64, arr/10, arr)

array([[50. , 51. , 52. , 53. , 54. , 55. , 56. , 57. , 58. , 59. ],
       [60. , 61. , 62. , 63. , 64. ,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])

argsort

In [63]:
import numpy as np

arr = np.array([10, -5, 6, -1])
print("Indexes: ", arr.argsort()) # Returns indexes
print("Sorted Array: ", arr[arr.argsort()])


Indexes:  [1 3 2 0]
Sorted Array:  [-5 -1  6 10]


Numpy Broadcasting
Start matching the dimensions backward (Right to Left)
  - Compatible - If same number appears or if one of them is 1
  - Incompatible - Otherwise

In [64]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([1, 2, 3])

print(arr_1 + arr_2)

[[2 4 6]
 [5 7 9]]


Reading CSV into Numpy Array
using loadtxt()

In [68]:
import numpy as np
 
# using loadtxt()
arr = np.loadtxt("data/nyc_weather.csv", delimiter=",", dtype='str')
print(arr)

[['EST' 'Temperature' 'DewPoint' 'Humidity' 'Sea Level PressureIn'
  'VisibilityMiles' 'WindSpeedMPH' 'PrecipitationIn' 'CloudCover'
  'Events' 'WindDirDegrees']
 ['1/1/2016' '38' '23' '52' '30.03' '10' '8' '0' '5' '' '281']
 ['1/2/2016' '36' '18' '46' '30.02' '10' '7' '0' '3' '' '275']
 ['1/3/2016' '40' '21' '47' '29.86' '10' '8' '0' '1' '' '277']
 ['1/4/2016' '25' '9' '44' '30.05' '10' '9' '0' '3' '' '345']
 ['1/5/2016' '20' '-3' '41' '30.57' '10' '5' '0' '0' '' '333']
 ['1/6/2016' '33' '4' '35' '30.5' '10' '4' '0' '0' '' '259']
 ['1/7/2016' '39' '11' '33' '30.28' '10' '2' '0' '3' '' '293']
 ['1/8/2016' '39' '29' '64' '30.2' '10' '4' '0' '8' '' '79']
 ['1/9/2016' '44' '38' '77' '30.16' '9' '8' 'T' '8' 'Rain' '76']
 ['1/10/2016' '50' '46' '71' '29.59' '4' '' '1.8' '7' 'Rain' '109']
 ['1/11/2016' '33' '8' '37' '29.92' '10' '' '0' '1' '' '289']
 ['1/12/2016' '35' '15' '53' '29.85' '10' '6' 'T' '4' '' '235']
 ['1/13/2016' '26' '4' '42' '29.94' '10' '10' '0' '0' '' '284']
 ['1/14/2016' '3